(() => {
  const cfg = window.NA_SUPABASE || {};
  const configured = typeof cfg.url === 'string' && /^https:\/\/[a-z0-9-]+\.supabase\.co$/.test(cfg.url) && typeof cfg.publishableKey === 'string' && cfg.publishableKey.startsWith('sb_publishable_') && window.supabase;
  const db = configured ? window.supabase.createClient(cfg.url, cfg.publishableKey, { auth: { persistSession: true, autoRefreshToken: true, detectSessionInUrl: true } }) : null;
  const $ = s => document.querySelector(s), $$ = s => [...document.querySelectorAll(s)];
  let sessionUser=null, profile=null, brands=[], faqs=[], leads=[], media=[];
  const settingKeys=['utility_message','brand_name','brand_tagline','hero_eyebrow','hero_title_html','hero_lead','hero_primary_text','hero_phone_text','trust_1','trust_2','trust_3','ecosystem_label','ecosystem_title_html','ecosystem_description','about_label','about_title_html','about_description','contact_label','contact_title_html','contact_description','faq_label','faq_title_html','faq_description','footer_description','seo_title','seo_description','hotline_text','hotline_href','email_text','email_href','address_text'];
  const titles={dashboard:['Tổng quan','Theo dõi và quản trị website Ngọc Anh.'],content:['Nội dung trang chủ','Chỉnh sửa nội dung hiển thị trên website.'],brands:['Thương hiệu','Quản lý hệ sinh thái thương hiệu.'],faqs:['Câu hỏi thường gặp','Quản lý câu hỏi và câu trả lời.'],leads:['Khách hàng đăng ký','Theo dõi yêu cầu tư vấn từ website.'],media:['Thư viện hình ảnh','Quản lý hình ảnh sử dụng trên website.'],seo:['SEO & liên hệ','Cập nhật thông tin Google và liên hệ.'],account:['Tài khoản','Thông tin tài khoản quản trị.']};
  function toast(msg,err=false){const el=$('#toast');el.textContent=msg;el.className='toast show'+(err?' error':'');setTimeout(()=>el.className='toast',2600)}
  function esc(v=''){return String(v).replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]))}
  function showLogin(){ $('#loginView').classList.remove('hidden'); $('#appView').classList.add('hidden'); if(!configured) $('#configWarning').classList.remove('hidden') }
  function showApp(){ $('#loginView').classList.add('hidden'); $('#appView').classList.remove('hidden'); $('#userEmail').textContent=sessionUser.email; $('#accountEmail').textContent=sessionUser.email; $('#userName').textContent=profile?.full_name||'Quản trị viên'; $('#userInitial').textContent=(profile?.full_name||sessionUser.email||'A').charAt(0).toUpperCase(); $('#accountRole').textContent=profile?.role||'admin'; loadAll(); }
  async function init(){ if(!configured) return showLogin(); const {data:{session}}=await db.auth.getSession(); if(!session) return showLogin(); sessionUser=session.user; if(!(await checkProfile())) return; showApp(); }
  async function checkProfile(){ const {data,error}=await db.from('profiles').select('*').eq('id',sessionUser.id).single(); if(error||!data||!['admin','editor'].includes(data.role)){await db.auth.signOut();toast('Tài khoản chưa được cấp quyền quản trị.',true);showLogin();return false} profile=data;return true }
  $('#loginForm').addEventListener('submit',async e=>{e.preventDefault();if(!configured)return toast('Chưa cấu hình Supabase.',true);const btn=e.submitter;btn.disabled=true;const {data,error}=await db.auth.signInWithPassword({email:$('#loginEmail').value.trim(),password:$('#loginPassword').value});btn.disabled=false;if(error)return toast(error.message,true);sessionUser=data.user;if(await checkProfile())showApp()});
  $('#forgotBtn').addEventListener('click',async()=>{if(!configured)return toast('Chưa cấu hình Supabase.',true);const email=$('#loginEmail').value.trim();if(!email)return toast('Nhập email trước.',true);const {error}=await db.auth.resetPasswordForEmail(email,{redirectTo:location.origin+location.pathname});toast(error?error.message:'Đã gửi email khôi phục mật khẩu.',!!error)});
  $('#logoutBtn').addEventListener('click',async()=>{await db.auth.signOut();location.reload()});
  $('#resetPasswordBtn').addEventListener('click',async()=>{const {error}=await db.auth.resetPasswordForEmail(sessionUser.email,{redirectTo:location.origin+location.pathname});toast(error?error.message:'Đã gửi email đổi mật khẩu.',!!error)});
  $('#mobileMenu').addEventListener('click',()=>$('.sidebar').classList.toggle('open'));
  $$('#sideNav a').forEach(a=>a.addEventListener('click',e=>{e.preventDefault();openView(a.dataset.view)}));
  $$('[data-jump]').forEach(b=>b.addEventListener('click',()=>openView(b.dataset.jump)));
  function openView(name){$$('.view').forEach(v=>v.classList.toggle('active',v.dataset.page===name));$$('#sideNav a').forEach(a=>a.classList.toggle('active',a.dataset.view===name));$('#pageTitle').textContent=titles[name][0];$('#pageSubtitle').textContent=titles[name][1];$('.sidebar').classList.remove('open');location.hash=name}
  async function loadAll(){await Promise.all([loadSettings(),loadBrands(),loadFaqs(),loadLeads(),loadMedia()]);updateStats()}
  async function loadSettings(){const {data,error}=await db.from('site_settings').select('key,value');if(error)return toast('Không tải được nội dung.',true);const obj=Object.fromEntries((data||[]).map(x=>[x.key,x.value]));[$('#contentForm'),$('#seoForm')].forEach(form=>{if(!form)return;[...form.elements].forEach(el=>{if(el.name)el.value=obj[el.name]||''})})}
  async function saveSettings(form){const rows=[...form.elements].filter(e=>e.name).map(e=>({key:e.name,value:e.value,updated_by:sessionUser.id,updated_at:new Date().toISOString()}));const {error}=await db.from('site_settings').upsert(rows,{onConflict:'key'});toast(error?error.message:'Đã lưu nội dung thành công.',!!error)}
  $('#contentForm').addEventListener('submit',e=>{e.preventDefault();saveSettings(e.currentTarget)});$('#seoForm').addEventListener('submit',e=>{e.preventDefault();saveSettings(e.currentTarget)});
  async function loadBrands(){const {data,error}=await db.from('brands').select('*').order('sort_order');if(error)return;brands=data||[];renderBrands()}
  function renderBrands(){if(!brands.length){$('#brandsTable').innerHTML='<div class="empty">Chưa có thương hiệu.</div>';return}$('#brandsTable').innerHTML=`<table class="data-table"><thead><tr><th>Ảnh</th><th>Thương hiệu</th><th>Danh mục</th><th>Thứ tự</th><th>Trạng thái</th><th></th></tr></thead><tbody>${brands.map(b=>`<tr><td><img class="thumb" src="${esc(b.image_url||'')}" alt=""></td><td><b>${esc(b.name)}</b><br><small>${esc(b.website_url||'')}</small></td><td>${esc(b.category_label||'')}</td><td>${b.sort_order||0}</td><td><span class="badge ${b.is_visible?'on':''}">${b.is_visible?'Hiển thị':'Đang ẩn'}</span></td><td><div class="row-actions"><button onclick="NA.editBrand('${b.id}')">Sửa</button><button class="danger" onclick="NA.deleteBrand('${b.id}')">Xóa</button></div></td></tr>`).join('')}</tbody></table>`}
  $('#addBrandBtn').addEventListener('click',()=>openBrandModal());
  function openBrandModal(item={}){openModal(item.id?'Sửa thương hiệu':'Thêm thương hiệu',[['name','Tên thương hiệu','text',item.name],['category_label','Nhãn danh mục','text',item.category_label],['description','Mô tả','textarea',item.description],['website_url','Website','url',item.website_url],['image_url','URL hình ảnh','url',item.image_url],['sort_order','Thứ tự','number',item.sort_order??0],['is_visible','Hiển thị','checkbox',item.is_visible!==false]],async vals=>{const payload={...vals,sort_order:Number(vals.sort_order||0),is_visible:!!vals.is_visible,updated_at:new Date().toISOString()};const q=item.id?db.from('brands').update(payload).eq('id',item.id):db.from('brands').insert(payload);const {error}=await q;if(error)return toast(error.message,true);toast('Đã lưu thương hiệu.');closeModal();loadBrands()})}
  async function deleteBrand(id){if(!confirm('Xóa thương hiệu này?'))return;const {error}=await db.from('brands').delete().eq('id',id);toast(error?error.message:'Đã xóa thương hiệu.',!!error);loadBrands()}
  async function loadFaqs(){const {data}=await db.from('faqs').select('*').order('sort_order');faqs=data||[];renderFaqs()}
  function renderFaqs(){if(!faqs.length){$('#faqsTable').innerHTML='<div class="empty">Chưa có câu hỏi.</div>';return}$('#faqsTable').innerHTML=`<table class="data-table"><thead><tr><th>Câu hỏi</th><th>Thứ tự</th><th>Trạng thái</th><th></th></tr></thead><tbody>${faqs.map(f=>`<tr><td><b>${esc(f.question)}</b><br><small>${esc(f.answer).slice(0,100)}...</small></td><td>${f.sort_order||0}</td><td><span class="badge ${f.is_visible?'on':''}">${f.is_visible?'Hiển thị':'Đang ẩn'}</span></td><td><div class="row-actions"><button onclick="NA.editFaq('${f.id}')">Sửa</button><button class="danger" onclick="NA.deleteFaq('${f.id}')">Xóa</button></div></td></tr>`).join('')}</tbody></table>`}
  $('#addFaqBtn').addEventListener('click',()=>openFaqModal());
  function openFaqModal(item={}){openModal(item.id?'Sửa câu hỏi':'Thêm câu hỏi',[['question','Câu hỏi','text',item.question],['answer','Câu trả lời','textarea',item.answer],['sort_order','Thứ tự','number',item.sort_order??0],['is_visible','Hiển thị','checkbox',item.is_visible!==false]],async vals=>{const payload={...vals,sort_order:Number(vals.sort_order||0),is_visible:!!vals.is_visible,updated_at:new Date().toISOString()};const q=item.id?db.from('faqs').update(payload).eq('id',item.id):db.from('faqs').insert(payload);const {error}=await q;if(error)return toast(error.message,true);toast('Đã lưu câu hỏi.');closeModal();loadFaqs()})}
  async function deleteFaq(id){if(!confirm('Xóa câu hỏi này?'))return;const {error}=await db.from('faqs').delete().eq('id',id);toast(error?error.message:'Đã xóa câu hỏi.',!!error);loadFaqs()}
  async function loadLeads(){const {data,error}=await db.from('leads').select('*').order('created_at',{ascending:false}).limit(1000);if(error)return;leads=data||[];renderLeads();renderRecent()}
  function filteredLeads(){const q=$('#leadSearch').value.trim().toLowerCase();return !q?leads:leads.filter(x=>(x.full_name+' '+x.phone+' '+(x.area||'')).toLowerCase().includes(q))}
  function renderLeads(){const list=filteredLeads();if(!list.length){$('#leadsTable').innerHTML='<div class="empty">Chưa có dữ liệu khách hàng.</div>';return}$('#leadsTable').innerHTML=`<table class="data-table"><thead><tr><th>Thời gian</th><th>Khách hàng</th><th>Khu vực</th><th>Sản phẩm</th><th>Trạng thái</th><th></th></tr></thead><tbody>${list.map(l=>`<tr><td>${new Date(l.created_at).toLocaleString('vi-VN')}</td><td><b>${esc(l.full_name)}</b><br><a href="tel:${esc(l.phone)}">${esc(l.phone)}</a></td><td>${esc(l.area||'')}</td><td>${esc(l.product_interest||'')}</td><td><span class="badge ${l.status==='new'?'new':'on'}">${statusName(l.status)}</span></td><td><div class="row-actions"><button onclick="NA.editLead('${l.id}')">Cập nhật</button></div></td></tr>`).join('')}</tbody></table>`}
  function statusName(s){return({new:'Mới',contacted:'Đã liên hệ',qualified:'Tiềm năng',closed:'Hoàn tất',invalid:'Không hợp lệ'})[s]||s}
  function renderRecent(){const box=$('#recentLeads');if(!leads.length){box.innerHTML='<div class="empty">Chưa có khách hàng mới.</div>';return}box.innerHTML=leads.slice(0,5).map(l=>`<div class="lead-card"><b>${esc(l.full_name)} · ${esc(l.phone)}</b><p>${esc(l.product_interest||'Chưa chọn sản phẩm')} — ${new Date(l.created_at).toLocaleString('vi-VN')}</p></div>`).join('')}
  $('#leadSearch').addEventListener('input',renderLeads);
  $('#exportLeads').addEventListener('click',()=>{const rows=[['Thời gian','Họ tên','Số điện thoại','Khu vực','Sản phẩm','Nội dung','Trạng thái'],...filteredLeads().map(l=>[l.created_at,l.full_name,l.phone,l.area,l.product_interest,l.message,statusName(l.status)])];const csv='\ufeff'+rows.map(r=>r.map(v=>'"'+String(v??'').replace(/"/g,'""')+'"').join(',')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download='khach-hang-ngoc-anh.csv';a.click()});
  function editLead(item){openModal('Cập nhật khách hàng',[['status','Trạng thái','select',item.status,['new|Mới','contacted|Đã liên hệ','qualified|Tiềm năng','closed|Hoàn tất','invalid|Không hợp lệ']],['admin_note','Ghi chú nội bộ','textarea',item.admin_note]],async vals=>{const {error}=await db.from('leads').update({...vals,updated_at:new Date().toISOString()}).eq('id',item.id);if(error)return toast(error.message,true);toast('Đã cập nhật khách hàng.');closeModal();loadLeads()})}
  async function loadMedia(){const {data,error}=await db.storage.from(cfg.storageBucket||'site-media').list('',{limit:100,sortBy:{column:'created_at',order:'desc'}});if(error){$('#mediaGrid').innerHTML='<div class="empty">Chưa tạo bucket site-media hoặc chưa cấp quyền.</div>';return}media=data||[];renderMedia()}
  function renderMedia(){const grid=$('#mediaGrid');if(!media.length){grid.innerHTML='<div class="empty">Chưa có hình ảnh.</div>';return}grid.innerHTML=media.filter(x=>x.name!=='.emptyFolderPlaceholder').map(x=>{const {data}=db.storage.from(cfg.storageBucket||'site-media').getPublicUrl(x.name);return `<article class="media-item"><img src="${data.publicUrl}" alt=""><div><b>${esc(x.name)}</b><button onclick="navigator.clipboard.writeText('${data.publicUrl}').then(()=>NA.toast('Đã sao chép URL.'))">Sao chép URL</button></div></article>`}).join('')}
  $('#mediaUpload').addEventListener('change',async e=>{for(const file of e.target.files){const safe=Date.now()+'-'+file.name.toLowerCase().replace(/[^a-z0-9._-]+/g,'-');const {error}=await db.storage.from(cfg.storageBucket||'site-media').upload(safe,file,{upsert:false});if(error)toast(error.message,true)}toast('Đã tải hình lên.');e.target.value='';loadMedia()});
  function updateStats(){$('#statBrands').textContent=brands.filter(x=>x.is_visible).length;$('#statFaqs').textContent=faqs.filter(x=>x.is_visible).length;$('#statLeads').textContent=leads.length;$('#statNewLeads').textContent=leads.filter(x=>x.status==='new').length}
  function openModal(title,fields,onSubmit){$('#modalTitle').textContent=title;$('#modalFields').innerHTML=fields.map(([name,label,type,val,opts])=>{if(type==='textarea')return `<label class="full">${label}<textarea name="${name}" rows="4">${esc(val||'')}</textarea></label>`;if(type==='checkbox')return `<label><span>${label}</span><input name="${name}" type="checkbox" ${val?'checked':''}></label>`;if(type==='select')return `<label>${label}<select name="${name}">${opts.map(o=>{const [v,t]=o.split('|');return `<option value="${v}" ${v===val?'selected':''}>${t}</option>`}).join('')}</select></label>`;return `<label>${label}<input name="${name}" type="${type}" value="${esc(val??'')}"></label>`}).join('');$('#modalForm').onsubmit=async e=>{e.preventDefault();const vals={};[...e.currentTarget.elements].forEach(el=>{if(el.name)vals[el.name]=el.type==='checkbox'?el.checked:el.value});await onSubmit(vals)};$('#editModal').showModal()}
  function closeModal(){$('#editModal').close()}$('#closeModal').onclick=closeModal;$('#cancelModal').onclick=closeModal;
  window.NA={editBrand:id=>openBrandModal(brands.find(x=>x.id===id)),deleteBrand,editFaq:id=>openFaqModal(faqs.find(x=>x.id===id)),deleteFaq,editLead:id=>editLead(leads.find(x=>x.id===id)),toast};
  init();
})();
